### ISSUE TITLE
[Feature Request] Translation

### ISSUE THREAD

**Issue by HydrelioxGitHub** [firstof9/lovelace-grocy-meal-plan-card#21]
Hello,

My girlfriend does not read English at all ! So it would be a great enhancement if we could provide some translation like it's implemented in the [Grocy Chore Lovelace Card](https://github.com/isabellaalstrom/lovelace-grocy-chores-card#advanced-options)

For exemple for this kind of string : 
"No meal plans for today"

Thank you for your time.

**Comment by firstof9** [comment]
Released in `1.0.4`
