### ISSUE TITLE
Adding Products breaks the Card

### ISSUE THREAD

**Issue by EpicElric** [firstof9/lovelace-grocy-meal-plan-card#28]
When adding a product to the meal plan instead of a recipe it causes the card to stop displaying anything.

**Comment by firstof9** [comment]
See #27

**Comment by Brouwertje** [comment]
It's not a mealplan card issue, but on the Grocy side. 

I found a workaround for the mealplan.

Create a section first. (name it food by example) When you create your mealplan, also add the created section to the meal for that day and the mealplan card works.

You can create a section at mealplan > Configure sections (top right)
