### ISSUE TITLE
Card shows HTML code after update.

### ISSUE THREAD

**Issue by Bovive** [firstof9/lovelace-grocy-meal-plan-card#31]
I updated from 1.0.4 to 1.0.5. The cards all show the recipe instructions in the card, but in HTML markup. This is true in a browser and also in the HA app. Downgrading back to 1.0.4 resolved the issue. HA is 2.23.5.4 and Grocy integration is 4.10.0. Attaching a screenshot for reference.

![screenshot](https://github.com/firstof9/lovelace-grocy-meal-plan-card/assets/4776549/7bb3e916-79e1-4270-8582-b8ba0910cdfd)

**Comment by firstof9** [comment]
This should be fixed in #30
