### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by HydrelioxGitHub** [firstof9/lovelace-grocy-meal-plan-card#37]
Is this repository opened to new feature suggestion ? Or is this prohibited due to main dev schedule ?

**Comment by firstof9** [comment]
I am 100% open to ideas, but I'm not really a Javascript guy.

**Comment by HydrelioxGitHub** [comment]
Do you know if it's possible to display another thing than the more-info ? Like a small card with the recipe on it. Or do an action on one tap like open the Grocy page with the recipe ?

**Comment by firstof9** [comment]
I am not sure honestly.

**Comment by idefxH** [comment]
And what about grouping meals per section? I have a section for lunch, another for dinner, and currently, if I have 2 meals for lunch and one for dinner, it sometimes show the dinner meal between the 2 meals for lunch.

**Comment by firstof9** [comment]
@idefxH please try the card in https://github.com/firstof9/lovelace-grocy-meal-plan-card/tree/section-sorting and let me know how that works for you.

Please continue the conversation in #40, thanks.
