### ISSUE TITLE
[Feature Request] Calendar Limit

### ISSUE THREAD

**Issue by HydrelioxGitHub** [firstof9/lovelace-grocy-meal-plan-card#7]
Hello and thank you for your work on this lovelace card. I don't know if it's the right place to ask for feature. Is it possible to define a number of day instead of just a count of meal. For example I would like to have in a card only the meal for today and tomorrow. But sometime I have 3 meal in the day sometime more, so 'count' property does not work in my usecase.

Other thing (maybe I should open another issue for this one ?), meal plans have sections now in gorcy. It could be great to have a filter on the card for these sections. For example, I want only to display in HA the meals for the breakfast section.

**Comment by firstof9** [comment]
I'll see what I can do.

**Comment by HydrelioxGitHub** [comment]
Hello, I've seen there was a release a few days ago. Thanks for it ! It does not filter but display section is a good point !

**Comment by firstof9** [comment]
`1.0.3` allows you to set the `daily` flag to show the current day's meal plan(s).
I'll work on a `section` filter shortly.

**Comment by firstof9** [comment]
I've release a beta version `1.0.4-b1` with section filtering.

**Comment by firstof9** [comment]
Released in `1.0.4`
